version: "3"

networks:
  humanscape:
    external: true

services:
  humanscape_backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: humanscape_backend
    tty: true
    stdin_open: true
    ports:
      - 8080:8080
    entrypoint: ./wait-for-it.sh humanscape_db:3306 -- sh run_for_deploy.sh
    environment:
      API_KEY: "${API_KEY}"
      URL: "${URL}"
      SECRET_KEY: "${SECRET_KEY}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_USER_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_HOST: humanscape_db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      
    networks:
      - humanscape

  humanscape_db:
    image: mysql:5.7.16
    container_name: humanscape_db
    restart: always
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-authentication-plugin=mysql_native_password
    environment:
      TZ: Asia/Seoul
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
    ports:
      - 3306:3306
    networks:
      - humanscape
